export const UPDATE_FORM_STATE = "UPDATE_FORM_STATE ";
// export const AUTH_ERROR_ACTION = "AUTH_ERROR_ACTION ";
// export const LOGOUT_ACTION = "LOGOUT_ACTION ";
// export const USERFORM_ACTION = 'USERFORM_ACTION';